### ISSUE TITLE
Make ActiveJob::SuckerPunchAdapter compatible with v2 syntax

### ISSUE THREAD

**Issue by dhh** [brandonhilkert/sucker_punch#159]
With the syntax change, the Rails adapter is failing with: `NoMethodError (undefined method `async' for #<ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper:0x007f8399ab82a8>):
`

It'd be great if we could fit a way to make that adapter still work even with v2. Seems a bit much to have a SuckerPunch2 adapter just for that.

Thoughts?

**Comment by brandonhilkert** [comment]
The last note under [ActiveJob integration](https://github.com/brandonhilkert/sucker_punch#active-job) mentions the module you can drag in to make it work with `2.0.0.beta1`. 

I was planning to release `2.0.0` this week and subsequently submit a PR to rails for proper integration with the new version. I have all the Rails changes setup locally. Another benefit is the syntax for performing a job in the future is now native. 

Will that timing work with the Rails 5 release?

**Comment by dhh** [comment]
Sweet. That'll work. We're probably going to do a beta2 next week. Then a
rc1 shortly there after. Final release in February.

Thanks again for your great work on Sucker Punch!

**Comment by brandonhilkert** [comment]
@dhh All good with this: https://github.com/rails/rails/pull/23284

**Comment by dhh** [comment]
👌
